import Head from "next/head";
import Navbar from "../component/Navbar";
import Slider from "../component/Slider";
import Body from "../component/HomePage/Body";
import SmallNavbar from "../component/SmallNavbar";
import "antd/dist/antd.css";
import { Layout } from "antd";
import React, { createContext,useState } from 'react'

const { Content } = Layout;

export const SiderContext=createContext()

export default function Home() {
  const [collapse,uncollapse]=useState(false)
  const [word,setWord]=useState(false)
  const toggle=()=>setWord(value=>!value)
  return (
    <>
    <SiderContext.Provider value={collapse}>
      <Head>
        <title>Dashboard HRMS Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossorigin="anonymous"
        ></link>
      </Head>
      <Layout>
        <Navbar changeWord={()=>setWord(toggle)} />
        <SmallNavbar />
        <Layout>
          <Slider val={word}/>
          <Layout>
            <Content>
              <Body />
            </Content>
          </Layout>
        </Layout>
      </Layout>
      </SiderContext.Provider>
    </>
  );
}
